In [1]:
import numpy as np

In [3]:
# 將list轉成array
box = [2,3,4]
box_Array = np.array(box)
box_Array

array([2, 3, 4])

In [156]:
# row = 2
col = 3

print(f"""
np.ndarray : 
{np.ndarray([row, col], dtype=np.float64)}
    
np.zeros   : 
{np.zeros([row, col], dtype=np.float64)}

np.ones    :
{np.ones([row, col], dtype=np.float64)}

np.linspace:
{np.linspace(0,10,6)}

np.arange  :
{np.arange(0,100,25)}

np.reshape :
{np.arange(0,100,25)}
    ||
    \/
{np.arange(0,100,25).reshape([2,2])}
""")


np.ndarray : 
[[228.61452489  41.2        228.61452489]
 [ 58.17423888 233.77715247  41.2       ]]
    
np.zeros   : 
[[0. 0. 0.]
 [0. 0. 0.]]

np.ones    :
[[1. 1. 1.]
 [1. 1. 1.]]

np.linspace:
[ 0.  2.  4.  6.  8. 10.]

np.arange  :
[ 0 25 50 75]

np.reshape :
[ 0 25 50 75]
    ||
    \/
[[ 0 25]
 [50 75]]



In [52]:
array_1 = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]], dtype=np.int64)
array_2 = np.array([[11,22,33],[44,55,66]], dtype=np.float64)

print(array_1.shape)
print(array_2.shape)

# 雖然shape不是相等，但在(..., 2, 3)的部分有對應到，依然可以相加，要注意的是這裡有點類似分配率的概念。
# 直接相加是 點加
array_1 + array_2

(2, 2, 3)
(2, 3)


array([[[12., 24., 36.],
        [48., 60., 72.]],

       [[12., 24., 36.],
        [48., 60., 72.]]])

In [57]:
# 所有元素相加
array_1.sum()

42

In [54]:
array_1.sum(axis=0)

array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int64)

In [55]:
array_1.sum(axis=1)

array([[5, 7, 9],
       [5, 7, 9]], dtype=int64)

In [56]:
array_1.sum(axis=2)

array([[ 6, 15],
       [ 6, 15]], dtype=int64)

In [66]:
# scalar可直接點乘
array_2 * 10

array([[110., 220., 330.],
       [440., 550., 660.]])

In [87]:
# shape不一樣不可以相乘，就算shape一樣，相乘也是對應的點相乘。
array_2 * np.array([[1, 2, 3]])

array([[ 11.,  44.,  99.],
       [ 44., 110., 198.]])

In [122]:
print(f"""
array_2 @ np.array([1,2,3] :
{array_2} dot {np.array([1,2,3])} = {array_2 @ np.array([1,2,3])}

np.matmul                  :
{np.matmul(array_2, np.array([[1],[2],[3]]))}
 
np.dot                     :
{array_2.shape, np.array([1,2,3]).shape}
{np.dot(array_2, np.array([1,2,3]))}

# 轉置一下array 
{np.array([1,2,3]).shape, array_2.T.shape}
{np.dot(np.array([1,2,3]), array_2.T)}

# 注意matrix的乘法要形狀對得起來才能做喔，ex. shape: (2,3) @ (3,3) = (2,3)
""")


array_2 @ np.array([1,2,3] :
[[11. 22. 33.]
 [44. 55. 66.]] dot [1 2 3] = [154. 352.]

np.matmul                  :
[[154.]
 [352.]]
 
np.dot                     :
((2, 3), (3,))
[154. 352.]

# 轉置一下array 
((3,), (3, 2))
[154. 352.]

# 注意matrix的乘法要形狀對得起來才能做喔，ex. shape: (2,3) @ (3,3) = (2,3)



In [126]:
print(f"""
看一下Data
{np.random.RandomState(0).randint(0,100,size=10)}

np.cumsum 累計計算
{np.cumsum(np.random.RandomState(0).randint(0,100,size=10))}
""")


看一下Data
[44 47 64 67 67  9 83 21 36 87]

np.cumsum 累計計算
[ 44  91 155 222 289 298 381 402 438 525]



In [127]:
# 假設常態分佈，並利用標準差找尋outlier
num_with_mean_50_and_std_5 = np.random.RandomState(0).randn(1000) * 5 + 50
num_with_mean_50_and_std_5_MEAN = np.mean(num_with_mean_50_and_std_5)
num_with_mean_50_and_std_5_STD = np.std(num_with_mean_50_and_std_5)

lower = num_with_mean_50_and_std_5_MEAN - num_with_mean_50_and_std_5_STD * 3
upper = num_with_mean_50_and_std_5_MEAN + num_with_mean_50_and_std_5_STD * 3

outlier = [x for x in num_with_mean_50_and_std_5 if x < lower or x > upper]
outlier_removed = [x for x in num_with_mean_50_and_std_5 if x >= lower and x <= upper]

print(len(outlier))
print(len(outlier_removed))

1
999


In [128]:
# 使用IQR找尋outlier
q25, q75 = np.percentile(num_with_mean_50_and_std_5, q=25), np.percentile(num_with_mean_50_and_std_5, q=75)
IQR = q75 - q25
QD = (q75 - q25) / 2
print("IQR: {:.2f}".format(IQR))
print("QD: {:.2f}".format(QD))
print("=====我是分隔線=====")

cut_off = IQR * 1.5
lower, upper = q25 - cut_off, q75 + cut_off
outlier = [x for x in num_with_mean_50_and_std_5 if x < lower or x > upper]
outlier_removed = [x for x in num_with_mean_50_and_std_5 if x >= lower and x <= upper]

print(len(outlier))
print(len(outlier_removed))

IQR: 6.53
QD: 3.26
=====我是分隔線=====
8
992
